---
# set_timezone/tasks/main.yml

- name: 'Set timezone in /etc/localtime'
  ansible.builtin.file:
    src: "../usr/share/zoneinfo/{{ desired_timezone }}"
    dest: '/etc/localtime'
    state: 'link'
    owner: 'root'
    group: 'root'
